version: "3.8"

services:
  mcp_server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - RF_API_KEY=${RF_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - LOG_LEVEL=WARNING
      - WORKERS=4
      - MAX_REQUESTS=1000
      - TIMEOUT=30
    volumes:
      - ./logs:/var/log/gunicorn
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
